"""
 An HTML page specialized for generating Pynorpa web pages.
"""

__author__ = "Nicolas Zwahlen"
__copyright__ = "Copyright 2024 N. Zwahlen"
__version__ = "1.0.0"

import logging
from HtmlPage import *
import DateTools

class PynorpaHtmlPage(HtmlPage):
    log = logging.getLogger('PynorpaHtmlPage')

    def __init__(self, sTitle, sPath = ''):
        self.sPath = sPath
        super().__init__(sTitle, 'http://www.tf79.ch/nature/style.css')
        self.head.addTag(HtmlComment(f'Generated by pynorpa.py on {DateTools.nowAsString()}'))
        self.head.addTag(MetaHtmlTag('author', 'Nicolas Zwahlen'))

    def buildHeader(self):
        tDivHeader = DivHtmlTag('header')
        tDivHeader.addTag(HtmlTag('small', 'Photos de nature &mdash; par Nicolas Zwahlen'))
        self.body.addTag(tDivHeader)

    def buildMenu(self):
        self.menu = DivHtmlTag('menu')
        self.body.addTag(self.menu)
        self.menu.addTag(HtmlTag('h1', '<a href="index.html">Accueil</a>'))
        self.menu.addTag(HtmlTag('h3', '<a href="tree.html">Classification</a>'))
        self.menu.addTag(HtmlTag('h3', '<a href="latest.html">Dernières photos</a>'))
        self.menu.addTag(HtmlTag('h3', '<a href="locations.html">Lieux</a>'))
        self.menu.addTag(HtmlTag('h3', '<a href="noms-latins.html">Noms latins</a>'))
        self.menu.addTag(HtmlTag('h3', '<a href="noms-verna.html">Noms communs</a>'))
        self.menu.addTag(HtmlTag('h3', '<a href="expeditions.html">Excursions</a>'))
        self.menu.addTag(HtmlTag('h3', '<a href="links.html">Liens</a>'))
        self.menu.addTag(HtmlTag('h3', '<a href="http://www.tf79.ch/">TF79.ch</a>'))

    def buildFooter(self):
        footer = DivHtmlTag('footer')
        date = DateTools.nowAsString('%d.%m.%Y')
        footer.addTag(HtmlTag('p', f'Copyleft Nicolas Zwahlen &mdash; {date} &mdash; Pynorpa v{__version__}'))
        self.body.addTag(footer)
