"""
 An HTML page specialized for generating Pynorpa web pages.
"""

__author__ = "Nicolas Zwahlen"
__copyright__ = "Copyright 2024 N. Zwahlen"
__version__ = "1.0.1"

import logging
import DateTools
from HtmlPage import *

class PynorpaHtmlPage(HtmlPage):
    log = logging.getLogger('PynorpaHtmlPage')
    version = '0'

    def __init__(self, sTitle, sPath = ''):
        self.sPath = sPath
        super().__init__(sTitle, 'http://www.tf79.ch/nature/style.css')
        self.addIconLink('http://www.tf79.ch/nature/favicon.ico')
        self.head.addTag(HtmlComment(f'Generated by pynorpa.py on {DateTools.nowAsString()}'))
        self.head.addTag(MetaHtmlTag('author', 'Nicolas Zwahlen'))
        
    def buildHeader(self):
        tDivHeader = DivHtmlTag('header')
        tDivHeader.addTag(HtmlTag('small', 'Photos de nature &mdash; par Nicolas Zwahlen'))
        self.body.addTag(tDivHeader)

    def buildMenu(self):
        self.menu = DivHtmlTag('menu')
        self.body.addTag(self.menu)
        self.menu.addTag(HtmlTag('h1', f'<a href="{self.sPath}index.html">Accueil</a>'))
        self.menu.addTag(HtmlTag('h3', f'<a href="{self.sPath}tree.html">Classification</a>'))
        self.menu.addTag(HtmlTag('h3', f'<a href="{self.sPath}latest.html">Dernières photos</a>'))
        self.menu.addTag(HtmlTag('h3', f'<a href="{self.sPath}locations.html">Lieux</a>'))
        self.menu.addTag(HtmlTag('h3', f'<a href="{self.sPath}noms-latins.html">Noms latins</a>'))
        self.menu.addTag(HtmlTag('h3', f'<a href="{self.sPath}noms-verna.html">Noms communs</a>'))
        self.menu.addTag(HtmlTag('h3', f'<a href="{self.sPath}expeditions.html">Excursions</a>'))
        self.menu.addTag(HtmlTag('h3', f'<a href="{self.sPath}liens.html">Liens</a>'))
        self.menu.addTag(HtmlTag('h3',  '<a href="http://www.tf79.ch/">TF79.ch</a>'))

    def buildFooter(self):
        footer = DivHtmlTag('footer')
        date = DateTools.nowAsString('%d.%m.%Y')
        footer.addTag(HtmlTag('p', f'Copyleft Nicolas Zwahlen &mdash; {date} &mdash; Pynorpa v{self.version}'))
        self.body.addTag(footer)

    def addOpenLayerHeaders(self):
        """Add scripts and CSS references for OpenLayer maps."""
        self.includeScript('js/OpenLayers-v5.3.0.js')
        self.includeScript('js/panorpa-maps.js')
        self.addCssLink('css/OpenLayers-v5.3.0.css')