"""
 An artifact with a name, kind and rarity
"""

__author__ = "Nicolas Zwahlen"
__copyright__ = "Copyright 2023 N. Zwahlen"
__version__ = "1.0.0"

from enum import Enum
import os
import random
from tkinter import PhotoImage
from NameGen import *
from Palette import *
from QomboImage import *

class OrKind(Enum):
    Generator  = 0
    Dice       = 1
    Star       = 2
    Spiral     = 3
    Ring       = 4
    Julia      = 5
    Objective  = 6

    def __str__(self):
        return self.name

class OrRarity(Enum):
    Common  = 0
    Unusual = 1
    Rare    = 2
    Mythic  = 3

    @staticmethod
    def random():
        return random.choices(list(OrRarity), OrRarity.weights())[0]

    @staticmethod
    def weights():
        return [81, 27, 9, 1]

    def __str__(self):
        return self.name

class Qombit:
    """An item that can be combined with another to evolve"""
    sImageDir = 'images/'
    oImage: PhotoImage
    oImageLarge: PhotoImage

    def __init__(self, sName: str, oKind: OrKind, iLevel: int, oRarity: OrRarity):
        self.sName = sName
        self.oKind = oKind
        self.iLevel = iLevel
        self.oRarity = oRarity
        self.oImage = None
        self.oImageLarge = None
        self.oMask = None
        self.aPalettes = [HeatPalette(), FluoPalette(), PinkGreenPalette(), SepiaPalette()]
        self.nameGen = NameGen(42)
        self.aNames = []
        for i in range(4):
            self.aNames.append(self.nameGen.generate())

    def getPalette(self) -> Palette:
        return self.aPalettes[self.oRarity.value]
    
    def getMask(self) -> QomboImage:
        if self.oMask is None:
            match self.oKind:
                case OrKind.Generator: self.oMask = TargetQomboImage()
                case OrKind.Star:      self.oMask = StarQomboImage()
                case OrKind.Dice:      self.oMask = DiceQomboImage()
                case OrKind.Spiral:    self.oMask = SpiralQomboImage()
                case OrKind.Ring:      self.oMask = RingQomboImage()
                case OrKind.Julia:     self.oMask = JuliaQomboImage()
        return self.oMask
    
    def evolve(self):
        """Result of combining this qombit with another one."""
        self.iLevel += 1
        self.oImage = None
        self.oImageLarge = None

    def canGenerate(self):
        """Check if this Qombit can generate others."""
        if self.oKind == OrKind.Generator:
            return True
        if self.iLevel >= 7:
            return True
        return False
    
    def getGeneratedKind(self):
        """Get the kind of Qombit generated by this one."""
        match self.oKind:
            case OrKind.Generator: return OrKind.Star
            case OrKind.Star:      return OrKind.Dice
            case OrKind.Dice:      return OrKind.Spiral
            case OrKind.Spiral:    return OrKind.Ring
            case OrKind.Ring:      return OrKind.Julia
        return None

    def generate(self):
        """Generate a new Qombit. Most Qombits can't do this."""
        if self.canGenerate():
            iLevel = 1
            oRarity = OrRarity.random()
            sName = self.aNames[oRarity.value]
            qombit = Qombit(sName, self.getGeneratedKind(), iLevel, oRarity)
            return qombit
        return None
    
    def getDescription(self) -> str:
        """Get a short text describing what to do with this qombit."""
        sDesc = 'Combine to evolve'
        if self.canGenerate():
            sDesc += '\nClick to create'
        return sDesc
    
    def getImageName(self, sPrefix = '') -> str:
        """Get the image filename for this qombit."""
        return self.sImageDir + self.oKind.name.lower() + sPrefix + '-r0' + str(self.oRarity.value) + '-l0' + str(self.iLevel) + '.png'
    
    def getImage(self) -> PhotoImage:
        """Get the PhotoImage for this qombit."""
        if self.oImage is None:
            sFilename = self.getImageName()
            self.oImage = self.generateImage(sFilename, 100)
        return self.oImage
    
    def getImageLarge(self) -> PhotoImage:
        """Get a larger PhotoImage for this qombit."""
        if self.oImageLarge is None:
            sFilename = self.getImageName('-large')
            self.oImageLarge = self.generateImage(sFilename, 160)
        return self.oImageLarge
    
    def generateImage(self, sFilename: str, iSize: int) -> PhotoImage:
        """Create a PhotoImage for this qombit with the specified filename and size."""
        if not os.path.exists(sFilename):
            oMask = self.getMask()
            oMask.generate(self.iLevel, iSize, iSize)
            oMask.toImage(self.getPalette(), sFilename)
        return PhotoImage(file = sFilename)
    
    def toJson(self):
        """Create a dict of this qombit for json export."""
        data = {}
        data['name'] = self.sName
        data['kind'] = self.oKind.name
        data['rarity'] = self.oRarity.name
        data['level'] = self.iLevel
        return data

    def __str__(self):
        return self.sName + ' level ' + str(self.iLevel) + ' ' + str(self.oRarity) + ' ' + str(self.oKind)
        
    def __eq__(self, other): 
        if not isinstance(other, Qombit):
            # don't attempt to compare against unrelated types
            return NotImplemented
        return self.oKind.value == other.oKind.value and self.oRarity.value == other.oRarity.value and self.iLevel == other.iLevel
    