"""
 An HTML page specialized for Highcharts rendering.
"""

__author__ = "Nicolas Zwahlen"
__copyright__ = "Copyright 2023 N. Zwahlen"
__version__ = "1.0.0"

import logging
import time
import json
from HtmlPage import *

class HighchartsHtmlPage(HtmlPage):
    log = logging.getLogger('HighchartsHtmlPage')

    def __init__(self, sTitle, sPath = ''):
        self.sPath = sPath
        self.sGalleryTitle = sTitle
        super().__init__(sTitle, 'http://www.tf79.ch/scripts/style.css')
        sTime = time.strftime('%Y.%m.%d %H:%M:%S', time.localtime(time.time()))
        self.head.addTag(HtmlComment('Generated by synthValues.py on ' + sTime))
        self.head.addTag(MetaHtmlTag('author', 'Nicolas Zwahlen'))
        self.includeScript('http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js')
        self.includeScript('http://code.highcharts.com/highcharts.js')
        self.includeScript('http://code.highcharts.com/modules/exporting.js')

    def addChart(self, name: str, jsonChart):
        """Add a div and JS script to display a Highcharts chart."""
        self.log.info('Adding Highcharts %s', name)
        divChart = DivHtmlTag(name)
        divChart.addAttr('style', 'width:1500px; height:900px;')
        self.add(divChart)

        js = 'jQuery(document).ready(function() {\n'
        js = js + 'var myChart = Highcharts.chart("' + name + '", ' + json.dumps(jsonChart, indent=2) + ');\n'
        js = js + '});'
        divScript = ScriptHtmlTag(js)
        self.add(divScript)
